# Python 機器學習從零至一 

> 數列運算

[數據交點](https://www.datainpoint.com) | 郭耀仁 <yaojenkuo@datainpoint.com>

In [1]:
import numpy as np

## Instructions

- The assignment will be disconnected if idling over 10 minutes, we can reactivate a new session by clicking the assignment link again.
- We've imported necessary modules at the top of each assignment.
- We've put necessary files(if any) in `/home/jovyan/data`.
- We've defined the names of functions/inputs/parameters for you.
- Write down your solution between the comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- It is NECESSARY to `return` the answer, tests will fail by just printing out the answer.
- It is known that `SyntaxError` and `IndentationError` might break our `test_runner.py` and results in a zero point grade. It is highly recommended testing your solution by calling functions/methods in notebook or running tests before submission.
- Running tests to see if your solutions are right:
    - File -> Save Notebook to save `exercises.ipynb`.
    - File -> New -> Terminal to open a Terminal.
    - Use command `python 01-exercises/test_runner.py` to run test.

## 01. Define a function named `add_intercepts` which horizontally combines a `(m, 1)` array of ones to a given array.

- Expected inputs: `np.ndarray`
- Expected outputs: `np.ndarray`

In [2]:
def add_intercepts(arr: np.ndarray) -> np.ndarray:
    """
    >>> A = np.array([5, 5, 6, 6]).reshape(-1, 1)
    >>> add_intercepts(A)
    array([[1, 5],
           [1, 5],
           [1, 6],
           [1, 6]])
    >>> B = np.zeros((5, 2), dtype=int)
    >>> add_intercepts(B)
    array([[1, 0, 0],
           [1, 0, 0],
           [1, 0, 0],
           [1, 0, 0],
           [1, 0, 0]])
    """
    ### BEGIN SOLUTION
    m = arr.shape[0]
    intercepts = np.ones(m, dtype=int).reshape(-1, 1)
    out = np.concatenate([intercepts, arr], axis=1)
    return out
    ### END SOLUTION

## 02. Define a function named `split_train_test` which splits a given array vertically according to specified parameters.

- Expected inputs: `np.ndarray`
- Expected outputs: `tuple`

In [3]:
def split_train_test(arr: np.ndarray, test_size: float) -> tuple:
    """
    >>> A = np.ones((10, 2))
    >>> A_train, A_test = split_train_test(A, test_size=0.3)
    >>> A_train.shape
    (7, 2)
    >>> A_test.shape
    (3, 2)
    >>> B = np.ones((20, 3))
    >>> B_train, B_test = split_train_test(B, test_size=0.4)
    >>> B_train.shape
    (12, 3)
    >>> B_test.shape
    (8, 3)
    """
    ### BEGIN SOLUTION
    m = arr.shape[0]
    test_index = int(m * test_size)
    arr_test, arr_train = np.split(arr, [test_index])
    return arr_train, arr_test
    ### END SOLUTION

## 03. Define a function named `is_invertible` which determines if an inverse matrix exists for a given matrix.

- Expected inputs: `np.ndarray`
- Expected outputs: `bool`

In [4]:
def is_invertible(arr: np.ndarray) -> bool:
    """
    >>> A = np.array([1, 2, 2, 4]).reshape(2, 2)
    >>> is_invertible(A)
    False
    >>> B = np.array([5, 5, 6, 6]).reshape(2, 2)
    >>> is_invertible(B)
    False
    >>> C = np.array([5, 6, 7, 8]).reshape(2, 2)
    >>> is_invertible(C)
    True
    """
    ### BEGIN SOLUTION
    try:
        np.linalg.inv(arr)
        return True
    except np.linalg.LinAlgError:
        return False
    ### END SOLUTION

## 04. Define a function named `create_diagonal_split_matrix` which generates a diagonal matrix given `n` as the order, `fill_int` as the elements outside the main diagonal and zeros as the main diagonal.

- Expected inputs: `int`
- Expected outputs: `np.ndarray`

In [5]:
def create_diagonal_split_matrix(n: int, fill_int: int) -> np.ndarray:
    """
    >>> create_diagonal_split_matrix(2, 5566)
    array([[   0, 5566],
           [5566,    0]])
    >>> create_diagonal_split_matrix(3, 55)
    array([[ 0, 55, 55],
           [55,  0, 55],
           [55, 55,  0]])
    >>> create_diagonal_split_matrix(4, 66)
    array([[ 0, 66, 66, 66],
           [66,  0, 66, 66],
           [66, 66,  0, 66],
           [66, 66, 66,  0]])
    """
    ### BEGIN SOLUTION
    arr_shape = (n, n)
    out_arr = np.full(shape=arr_shape, fill_value=fill_int)
    diags = np.diagonal(out_arr)
    minus_arr = -np.diag(diags)
    out_arr += minus_arr
    return out_arr
    ### END SOLUTION

## 05. Define a function named `create_square_matrix` which generates a square matrix with elements equal to the multiplication of row numbers and column numbers.

- Expected inputs: `int`
- Expected outputs: `np.ndarray`

In [6]:
def create_square_matrix(n: int) -> np.ndarray:
    """
    >>> create_square_matrix(3)
    array([[1, 2, 3],
           [2, 4, 6],
           [3, 6, 9]])
    >>> create_square_matrix(4)
    array([[ 1,  2,  3,  4],
           [ 2,  4,  6,  8],
           [ 3,  6,  9, 12],
           [ 4,  8, 12, 16]])
    >>> create_square_matrix(5)
    array([[ 1,  2,  3,  4,  5],
           [ 2,  4,  6,  8, 10],
           [ 3,  6,  9, 12, 15],
           [ 4,  8, 12, 16, 20],
           [ 5, 10, 15, 20, 25]])
    """
    ### BEGIN SOLUTION
    arr = np.arange(1, n + 1).reshape(-1, 1)
    out = arr.dot(arr.T)
    return out
    ### END SOLUTION