# Python 機器學習從零至一 

> 以 Scikit-Learn 做機器學習

[數據交點](https://www.datainpoint.com) | 郭耀仁 <yaojenkuo@datainpoint.com>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures

## Instructions

- The assignment will be disconnected if idling over 10 minutes, we can reactivate a new session by clicking the assignment link again.
- We've imported necessary modules at the top of each assignment.
- We've put necessary files(if any) in `/home/jovyan/data`.
- We've defined the names of functions/inputs/parameters for you.
- Write down your solution between the comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- It is NECESSARY to `return` the answer, tests will fail by just printing out the answer.
- It is known that `SyntaxError` and `IndentationError` might break our `test_runner.py` and results in a zero point grade. It is highly recommended testing your solution by calling functions/methods in notebook or running tests before submission.
- Running tests to see if your solutions are right:
    - File -> Save Notebook to save `exercises.ipynb`.
    - File -> New -> Terminal to open a Terminal.
    - Use command `python 02-exercises/test_runner.py` to run test.

## 01. Given `/home/jovyan/data/titanic/train.csv`, extract `Survived` as target vector and other variables as feature matrix.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [2]:
def extract_titanic_X_y() -> np.ndarray:
    """
    >>> titanic_X, titanic_y = extract_titanic_X_y()
    >>> type(titanic_X)
    'numpy.ndarray'
    >>> type(titanic_y)
    'numpy.ndarray'
    >>> titanic_X.shape
    (891,11)
    >>> titanic_y.shape
    (891,)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 02. Given `/home/jovyan/data/house-prices/train.csv`, extract `SalePrice` as target vector and other variables as feature matrix.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [3]:
def extract_house_prices_X_y() -> np.ndarray:
    """
    >>> house_prices_X, house_prices_y = extract_house_prices_X_y()
    >>> type(house_prices_X)
    'numpy.ndarray'
    >>> type(house_prices_y)
    'numpy.ndarray'
    >>> house_prices_X.shape
    (1460, 80)
    >>> house_prices_y.shape
    (1460,)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 03. Given `/home/jovyan/data/titanic/train.csv` in working directory, extract `Fare` as the feature matrix and apply `StandardScaler` to it.

- Expected inputs: None.
- Expected outputs: `ndarray`

In [4]:
def get_standard_scaled_fare() -> np.ndarray:
    """
    >>> standard_scaled_fare = get_standard_scaled_fare()
    >>> type(standard_scaled_fare)
    'numpy.ndarray'
    >>> standard_scaled_fare.shape
    (891, 1)
    >>> standard_scaled_fare[:5]
    array([[-0.50244517],
           [ 0.78684529],
           [-0.48885426],
           [ 0.42073024],
           [-0.48633742]])
    >>> standard_scaled_fare.std()
    1.0
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 04. Given `/home/jovyan/data/house-prices/train.csv`, extract `GrLivArea` as the feature matrix and apply `MinMaxScaler` to it. 

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [6]:
def get_min_max_scaled_gr_liv_area() -> np.ndarray:
    """
    >>> min_max_scaled_gr_liv_area = get_min_max_scaled_gr_liv_area()
    >>> type(min_max_scaled_gr_liv_area)
    'numpy.ndarray'
    >>> min_max_scaled_gr_liv_area.shape
    (1460, 1)
    >>> min_max_scaled_gr_liv_area[:5]
    array([[0.25923135],
           [0.17483044],
           [0.27354936],
           [0.26055011],
           [0.35116805]])
    >>> min_max_scaled_gr_liv_area.max()
    1.0
    >>> min_max_scaled_gr_liv_area.min()
    0.0
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 05. Given `/home/jovyan/data/house-prices/train.csv`, extract `GrLivArea` as the feature matrix and apply `PolynomialFeatures` to it with a hyperparameter `degree=3` adding intercepts, linear, and non-linear attributes to the feature matrix. 

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [7]:
def get_polynomial_gr_liv_area() -> np.ndarray:
    """
    >>> polynomial_gr_liv_area = get_polynomial_gr_liv_area()
    >>> type(polynomial_gr_liv_area)
    'numpy.ndarray'
    >>> polynomial_gr_liv_area.shape
    (1460, 4)
    >>> polynomial_gr_liv_area[:5]
    array([[1.00000000e+00, 1.71000000e+03, 2.92410000e+06, 5.00021100e+09],
           [1.00000000e+00, 1.26200000e+03, 1.59264400e+06, 2.00991673e+09],
           [1.00000000e+00, 1.78600000e+03, 3.18979600e+06, 5.69697566e+09],
           [1.00000000e+00, 1.71700000e+03, 2.94808900e+06, 5.06186881e+09],
           [1.00000000e+00, 2.19800000e+03, 4.83120400e+06, 1.06189864e+10]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION