# Python 機器學習從零至一 

> 梯度遞減

[數據交點](https://www.datainpoint.com) | 郭耀仁 <yaojenkuo@datainpoint.com>

In [ ]:
import unittest
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

## 練習題指引

- 練習題閒置超過 15 分鐘會自動斷線，只要重新點選練習題連結即可重新啟動。
- 第一個程式碼儲存格會將可能用得到的模組載入。
- 如果練習題需要載入檔案，檔案存放於練習題的工作目錄。
- 練習題已經給定函數、類別、預期輸入或參數名稱，我們只需要寫作程式區塊。同時也給定函數的類別提示，說明預期輸入以及預期輸出的類別。
- 說明（Docstring）會描述測試如何進行，閱讀說明能夠暸解預期輸入以及預期輸出之間的關係，幫助我們更快解題。
- 請在 `### BEGIN SOLUTION` 與 `### END SOLUTION` 這兩個註解之間寫作函數或者類別的程式區塊。
- 將預期輸出放置在 `return` 保留字之後，若只是用 `print()` 函數將預期輸出印出無法通過測試。
- 語法錯誤（`SyntaxError`）或縮排錯誤（`IndentationError`）等將會導致測試失效，測試之前應該先在筆記本使用函數觀察是否與說明（Docstring）描述的功能相符。
- 執行測試：點選上方選單的 Kernel -> Restart & Run All -> Restart and Run All Cells

## 01. 載入 `regression` 中的 `train.csv`

定義函數 `import_regression()` 將位於 `regression` 資料夾的 `train.csv` 載入。

- 使用 `pd.read_csv()` 函數。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def import_regression() -> pd.core.frame.DataFrame:
    """
    >>> train = import_regression()
    >>> type(train)
    pandas.core.frame.DataFrame
    >>> train.shape
    (15, 2)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 02. 選擇 `regression` 目標陣列與特徵矩陣

定義函數 `extract_target_array_feature_matrix_regression()` 以 `train.csv` 中的 `y` 作為目標陣列 $y$、`x1` 作為特徵矩陣 $X$

- 使用 `import_regression()` 函數。
- 運用選擇欄位技巧。
- 注意特徵矩陣外型。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def extract_target_array_feature_matrix_regression() -> tuple:
    """
    >>> y, X = extract_target_array_feature_matrix_regression()
    >>> type(y)
    numpy.ndarray
    >>> type(X)
    numpy.ndarray
    >>> y.shape
    (15,)
    >>> X.shape
    (15, 1)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 03. 為 `regression` 特徵矩陣添加截距

定義函數 `add_intercepts_for_feature_matrix_regression()` 為特徵矩陣添加截距 $x_0 = 1$

- 將預期輸出寫在 `return` 之後。

In [ ]:
def add_intercepts_for_feature_matrix_regression(X: np.ndarray) -> np.ndarray:
    """
    >>> y, X = extract_target_array_feature_matrix_regression()
    >>> X = add_intercepts_for_feature_matrix_regression(X)
    >>> type(X)
    numpy.ndarray
    >>> X.shape
    (15, 2)
    >>> X
    array([[ 1,  1],
           [ 1,  2],
           [ 1,  3],
           [ 1,  4],
           [ 1,  5],
           [ 1,  6],
           [ 1,  7],
           [ 1,  8],
           [ 1,  9],
           [ 1, 10],
           [ 1, 11],
           [ 1, 12],
           [ 1, 13],
           [ 1, 14],
           [ 1, 15]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 04. 使用梯度遞減找出 `regression` 的規則 $w$ 

定義函數 `find_w_with_gradient_descent_regression()` 找出目標陣列 $y$、特徵矩陣 $X$ 之間的規則 $w$

- 使用梯度遞減。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def find_w_with_gradient_descent_regression(X: np.ndarray, y: np.ndarray) -> tuple:
    """
    >>> y, X = extract_target_array_feature_matrix_regression()
    >>> X = add_intercepts_for_feature_matrix_regression(X)
    >>> w0, w1 = find_w_with_gradient_descent_regression(X, y)
    >>> w0
    54.45457559513067
    >>> w1
    66.0529262315208
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 05. 載入 `house-prices` 中的 `train.csv` 與 `test.csv`

定義函數 `import_house_prices()` 將位於 `house-prices` 路徑的 `train.csv` 與 `test.csv` 載入。

來源：<https://www.kaggle.com/c/house-prices-advanced-regression-techniques>

- 運用絕對路徑。
- 使用 `pd.read_csv()` 函數。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def import_house_prices() -> tuple:
    """
    >>> train, test = import_house_prices()
    >>> type(train)
    pandas.core.frame.DataFrame
    >>> type(test)
    pandas.core.frame.DataFrame
    >>> train.shape
    (1460, 81)
    >>> test.shape
    (1459, 80)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 06. 選擇 `house-prices` 目標陣列與特徵矩陣

定義函數 `extract_target_array_feature_matrix_house_prices()` 以 `train.csv` 中的 `SalePrice` 作為目標陣列 $y$、`OverallQual` 以及 `GrLivArea` 作為特徵矩陣 $X$

- 使用 `import_house_prices()` 函數。
- 運用選擇欄位技巧。
- 注意特徵矩陣外型。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def extract_target_array_feature_matrix_house_prices() -> tuple:
    """
    >>> y, X = extract_target_array_feature_matrix_house_prices()
    >>> type(y)
    numpy.ndarray
    >>> type(X)
    numpy.ndarray
    >>> y.shape
    (1460,)
    >>> X.shape
    (1460, 2)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 07. 對 `house-prices` 特徵矩陣進行最大最小標準化

定義函數 `standardize_feature_matrix_house_prices()` 對特徵矩陣進行最大最小標準化。

- 使用 `sklearn.preprocessing.MinMaxScaler`
- 將預期輸出寫在 `return` 之後。

In [ ]:
def standardize_feature_matrix_house_prices(X: np.ndarray) -> np.ndarray:
    """
    >>> y, X = extract_target_array_feature_matrix_house_prices()
    >>> X_scaled = standardize_feature_matrix_house_prices(X)
    >>> type(X_scaled)
    numpy.ndarray
    >>> X_scaled.shape
    (1460, 2)
    >>> X_scaled
    array([[0.66666667, 0.25923135],
           [0.55555556, 0.17483044],
           [0.66666667, 0.27354936],
           ...,
           [0.66666667, 0.37792012],
           [0.44444444, 0.14016579],
           [0.44444444, 0.17370008]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 08. 為 `house-prices` 特徵矩陣添加截距

定義函數 `add_intercepts_for_feature_matrix_house_prices()` 為特徵矩陣添加截距 $x_0 = 1$

- 將預期輸出寫在 `return` 之後。

In [ ]:
def add_intercepts_for_feature_matrix_house_prices(X: np.ndarray) -> np.ndarray:
    """
    >>> y, X = extract_target_array_feature_matrix_house_prices()
    >>> X_scaled = standardize_feature_matrix_house_prices(X)
    >>> X_scaled = add_intercepts_for_feature_matrix_house_prices(X_scaled)
    >>> type(X_scaled)
    numpy.ndarray
    >>> X_scaled.shape
    (1460, 3)
    >>> X_scaled
    array([[1.        , 0.66666667, 0.25923135],
           [1.        , 0.55555556, 0.17483044],
           [1.        , 0.66666667, 0.27354936],
           ...,
           [1.        , 0.66666667, 0.37792012],
           [1.        , 0.44444444, 0.14016579],
           [1.        , 0.44444444, 0.17370008]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 09. 切割 `house-prices` 訓練與驗證資料

定義函數 `split_train_valid_house_prices()` 將 $y$ 與 $X$ 切割為訓練與驗證資料。

- 使用 `train_test_split(test_size=0.3, random_state=42)` 函數。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def split_train_valid_house_prices(X: np.ndarray, y: np.ndarray) -> tuple:
    """
    >>> y, X = extract_target_array_feature_matrix_house_prices()
    >>> X_scaled = standardize_feature_matrix_house_prices(X)
    >>> X_scaled = add_intercepts_for_feature_matrix_house_prices(X_scaled)
    >>> X_train, X_valid, y_train, y_valid = split_train_valid_house_prices(X_scaled, y)
    >>> X_train.shape
    (1022, 3)
    >>> X_valid.shape
    (438, 3)
    >>> y_train.shape
    (1022,)
    >>> y_valid.shape
    (438,)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 10. 使用梯度遞減找出 `house-prices` 的規則 $w$ 

定義函數 `find_w_with_gradient_descent_house_prices()` 找出目標陣列 $y$、特徵矩陣 $X$ 之間的規則 $w$

- 使用梯度遞減。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def find_w_with_gradient_descent_house_prices(X: np.ndarray, y: np.ndarray) -> np.ndarray:
    """
    >>> y, X = extract_target_array_feature_matrix_house_prices()
    >>> X_scaled = standardize_feature_matrix_house_prices(X)
    >>> X_scaled = add_intercepts_for_feature_matrix_house_prices(X_scaled)
    >>> X_train, X_valid, y_train, y_valid = split_train_valid_house_prices(X_scaled, y)
    >>> w = find_w_with_gradient_descent_house_prices(X_train, y_train)
    >>> w
    array([-48286.9320018 , 295454.960101  , 272007.71844698])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 10. 以梯度遞減找出的 $w$ 預測位於 `house-prices` 路徑的 `test.csv`

定義函數 `predict_sale_price()` 能夠依據 `OverallQual` 與 `GrLivArea` 預測 `test.csv` 的 `SalePrice`

- 使用 `import_house_prices()` 函數。
- 使用 `extract_target_array_feature_matrix_house_prices()` 函數。
- 使用 `standardize_feature_matrix_house_prices()` 函數。
- 使用 `add_intercepts_for_feature_matrix_house_prices()` 函數。
- 使用 `split_train_valid_house_prices()` 函數。
- 使用 `find_w_with_gradient_descent_house_prices()` 函數。
- 將預期輸出寫在 `return` 之後。

In [ ]:
def predict_sale_price(X_test: pd.core.frame.DataFrame) -> pd.core.frame.DataFrame:
    """
    >>> train, test = import_house_prices()
    >>> X_test = test[["Id", "OverallQual", "GrLivArea"]]
    >>> predict_sale_price(X_test)
    
    >>> predict_sale_price(X_test)
            Id      SalePrice
    0     1461  111399.202352
    1     1462  169351.111050
    2     1463  153929.419424
    3     1464  185307.195217
    4     1465  232164.684760
    ...    ...            ...
    1454  2915   89943.209805
    1455  2916   89943.209805
    1456  2917  130430.459105
    1457  2918  115692.839546
    1458  2919  241112.285317

    [1459 rows x 2 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 練習題結束，以下儲存格為批改測試使用。

In [ ]:
class TestGradientDescent(unittest.TestCase):
    def test_01_import_regression(self):
        train = import_regression()
        self.assertIsInstance(train, pd.core.frame.DataFrame)
        self.assertEqual(train.shape, (15, 2))
    def test_02_extract_target_array_feature_matrix_regression(self):
        y, X = extract_target_array_feature_matrix_regression()
        self.assertIsInstance(y, np.ndarray)
        self.assertIsInstance(X, np.ndarray)
        self.assertEqual(y.shape, (15,))
        self.assertEqual(X.shape, (15, 1))
    def test_03_add_intercepts_for_feature_matrix_regression(self):
        y, X = extract_target_array_feature_matrix_regression()
        X = add_intercepts_for_feature_matrix_regression(X)
        self.assertIsInstance(X, np.ndarray)
        self.assertEqual(X.shape, (15, 2))
    def test_04_find_w_with_gradient_descent_regression(self):
        y, X = extract_target_array_feature_matrix_regression()
        X = add_intercepts_for_feature_matrix_regression(X)
        w0, w1 = find_w_with_gradient_descent_regression(X, y)
        self.assertTrue(w0 > 50)
        self.assertTrue(w0 < 60)
        self.assertTrue(w1 > 65)
        self.assertTrue(w1 < 70)
    def test_05_import_house_prices(self):
        train, test = import_house_prices()
        self.assertIsInstance(train, pd.core.frame.DataFrame)
        self.assertIsInstance(test, pd.core.frame.DataFrame)
        self.assertEqual(train.shape, (1460, 81))
        self.assertEqual(test.shape, (1459, 80))
    def test_06_extract_target_array_feature_matrix_house_prices(self):
        y, X = extract_target_array_feature_matrix_house_prices()
        self.assertEqual(y.shape, (1460,))
        self.assertEqual(X.shape, (1460, 2))
    def test_07_standardize_feature_matrix_house_prices(self):
        y, X = extract_target_array_feature_matrix_house_prices()
        X_scaled = standardize_feature_matrix_house_prices(X)
        self.assertIsInstance(X_scaled, np.ndarray)
        self.assertEqual(X_scaled.shape, (1460, 2))
        self.assertTrue(X_scaled[:, 0].max() <= 1)
        self.assertTrue(X_scaled[:, 0].min() >= 0)
        self.assertTrue(X_scaled[:, 1].max() <= 1)
        self.assertTrue(X_scaled[:, 1].min() >= 0)
    def test_08_add_intercepts_for_feature_matrix_house_prices(self):
        y, X = extract_target_array_feature_matrix_house_prices()
        X = standardize_feature_matrix_house_prices(X)
        X = add_intercepts_for_feature_matrix_house_prices(X)
        self.assertEqual(X.shape, (1460, 3))
    def test_09_split_train_valid_house_prices(self):
        y, X = extract_target_array_feature_matrix_house_prices()
        X = standardize_feature_matrix_house_prices(X)
        X = add_intercepts_for_feature_matrix_house_prices(X)
        X_train, X_valid, y_train, y_valid = split_train_valid_house_prices(X, y)
        self.assertEqual(X_train.shape, (1022, 3))
        self.assertEqual(X_valid.shape, (438, 3))
        self.assertEqual(y_train.shape, (1022,))
        self.assertEqual(y_valid.shape, (438,))
    def test_10_find_w_with_gradient_descent_house_prices(self):
        y, X = extract_target_array_feature_matrix_house_prices()
        X = standardize_feature_matrix_house_prices(X)
        X = add_intercepts_for_feature_matrix_house_prices(X)
        X_train, X_valid, y_train, y_valid = split_train_valid_house_prices(X, y)
        w = find_w_with_gradient_descent_house_prices(X_train, y_train)
        self.assertEqual(w.shape, (3,))
        self.assertTrue(w[0] < 0)
        self.assertTrue(w[1] > 0)
        self.assertTrue(w[2] > 0)
    def test_11_predict_sale_price(self):
        train, test = import_house_prices()
        X_test = test[["Id", "OverallQual", "GrLivArea"]]
        sale_price = predict_sale_price(X_test)
        self.assertIsInstance(sale_price, pd.core.frame.DataFrame)
        self.assertEqual(sale_price.shape, (1459, 2))
        
suite = unittest.TestLoader().loadTestsFromTestCase(TestGradientDescent)
runner = unittest.TextTestRunner(verbosity=2)
test_results = runner.run(suite)
number_of_failures = len(test_results.failures)
number_of_errors = len(test_results.errors)
number_of_test_runs = test_results.testsRun
number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)

In [ ]:
print("你在梯度遞減的 {} 個問題中答對了 {} 題。".format(number_of_test_runs, number_of_successes))