# Python 機器學習從零至一 

> 數值預測的任務

[數據交點](https://www.datainpoint.com) | 郭耀仁 <yaojenkuo@datainpoint.com>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

## Instructions

- The assignment will be disconnected if idling over 10 minutes, we can reactivate a new session by clicking the assignment link again.
- We've imported necessary modules at the top of each assignment.
- We've put necessary files(if any) in `/home/jovyan/data`.
- We've defined the names of functions/inputs/parameters for you.
- Write down your solution between the comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- It is NECESSARY to `return` the answer, tests will fail by just printing out the answer.
- It is known that `SyntaxError` and `IndentationError` might break our `test_runner.py` and results in a zero point grade. It is highly recommended testing your solution by calling functions/methods in notebook or running tests before submission.
- Running tests to see if your solutions are right:
    - File -> Save Notebook to save `exercises.ipynb`.
    - File -> New -> Terminal to open a Terminal.
    - Use command `python 03-exercises/test_runner.py` to run test.

## 01. Given `/home/jovyan/data/house-prices/test.csv` and `/home/jovyan/data/house-prices/train.csv`, create a chimp model to predict `SalePrice` for each observation in `test.csv`.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [ ]:
def predict_sale_price_chimp_model() -> np.ndarray:
    """
    >>> sale_price_chimp_model = predict_sale_price_chimp_model()
    >>> type(sale_price_chimp_model)
    'numpy.ndarray'
    >>> sale_price_chimp_model.shape
    (1459,)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 02. Given `/home/jovyan/data/house-prices/test.csv` and `/home/jovyan/data/house-prices/train.csv`, create an expert model to predict `SalePrice` according to `OverallQual` for each observation in `test.csv`.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [ ]:
def predict_sale_price_expert_model() -> np.ndarray:
    """
    >>> sale_price_expert_model = predict_sale_price_expert_model()
    >>> type(sale_price_expert_model)
    'numpy.ndarray'
    >>> sale_price_expert_model.shape
    (1459,)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 03. Given `/home/jovyan/data/house-prices/train.csv`, extract `GrLivArea` as the feature matrix and apply Scikit-Learn's `LinearRegression` to predict `SalePrice`. Return the intercept and coefficients in an array.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [ ]:
def predict_sale_price_sklearn_model() -> np.ndarray:
    """
    >>> sale_price_sklearn_model = predict_sale_price_sklearn_model()
    >>> type(sale_price_sklearn_model)
    'numpy.ndarray'
    >>> sale_price_sklearn_model
    array([18569.02585649,   107.13035897])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 04. Given `/home/jovyan/data/house-prices/train.csv`, extract `GrLivArea` as the feature matrix and apply your self-defined normal equation model to predict `SalePrice`. Return the intercept and coefficients in an array.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [ ]:
def predict_sale_price_normal_equation_model() -> np.ndarray:
    """
    >>> sale_price_normal_equation_model = predict_sale_price_normal_equation_model()
    >>> type(sale_price_normal_equation_model)
    'numpy.ndarray'
    >>> sale_price_normal_equation_model
    array([18569.02585649,   107.13035897])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 05. Given `/home/jovyan/data/nba/player_stats.csv` extract `apg` and `rpg` as the feature matrix and apply Scikit-Learn's `LinearRegression` to predict `heightMeters`. Return the intercept and coefficients in an array.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [ ]:
def predict_height_meters_sklearn_model() -> np.ndarray:
    """
    >>> height_meters_sklearn_model = predict_height_meters_sklearn_model()
    >>> type(height_meters_sklearn_model)
    'numpy.ndarray'
    >>> height_meters_sklearn_model
    array([ 1.95251514, -0.02754199,  0.02407157])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 06. Given `/home/jovyan/data/nba/player_stats.csv` extract `apg` and `rpg` as the feature matrix and apply self-defined gradient descent model to predict `heightMeters`. Return the intercept and coefficients in an array.

- Expected inputs: None.
- Expected outputs: `ndarray`.

In [ ]:
def predict_height_meters_gradient_descent_model() -> np.ndarray:
    """
    >>> height_meters_grdient_descent_model = predict_height_meters_gradient_descent_model()
    >>> type(height_meters_gradient_descent_model)
    'numpy.ndarray'
    >>> height_meters_gradient_descent_model.size
    3
    >>> height_meters_gradient_descent_model[1] < 0
    True
    >>> height_meters_gradient_descent_model[2] > 0
    True
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION